sga index --no-reverse -a ropebwt -t 1 AD09WVACXX_PE.fastq & 
sga index --no-reverse -a ropebwt -t 1 AD09WVACXX_SE.fastq & 
sga index --no-reverse -a ropebwt -t 1 ADO10785S2_PE.fastq & 
sga index --no-reverse -a ropebwt -t 1 ADO10785S2_SE.fastq & 
sga index --no-reverse -a ropebwt -t 1 ADO10785S3_PE.fastq & 
sga index --no-reverse -a ropebwt -t 1 ADO10785S3_SE.fastq & 
sga index --no-reverse -a ropebwt -t 1 BCOT1RACXX_PE.fastq & 
sga index --no-reverse -a ropebwt -t 1 BCOT1RACXX_SE.fastq & 
sga index --no-reverse -a ropebwt -t 1 C4BCWACXX_PE.fastq & 
sga index --no-reverse -a ropebwt -t 1 C4BCWACXX_SE.fastq & 
sga index --no-reverse -a ropebwt -t 1 D0F34ACXX_PE.fastq & 
sga index --no-reverse -a ropebwt -t 1 D0F34ACXX_SE.fastq & 
sga index --no-reverse -a ropebwt -t 1 D1259ACXX.fastq & 
sga index --no-reverse -a ropebwt -t 1 G0LLCGL01.fastq & 
sga index --no-reverse -a ropebwt -t 1 G0LLCGL02.fastq & 
sga index --no-reverse -a ropebwt -t 1 GZ290HF01.fastq & 
sga index --no-reverse -a ropebwt -t 1 GZ290HF02.fastq & 
sga index --no-reverse -a ropebwt -t 1 GZ29Y3E01.fastq & 
sga index --no-reverse -a ropebwt -t 1 GZ29Y3E02.fastq & 
sga index --no-reverse -a ropebwt -t 1 liver_PE.fastq & 
sga index --no-reverse -a ropebwt -t 1 liver_SE.fastq & 
sga index --no-reverse -a ropebwt -t 1 spleen1_PE.fastq & 
sga index --no-reverse -a ropebwt -t 1 spleen1_SE.fastq & 
sga index --no-reverse -a ropebwt -t 1 spleen2_PE.fastq & 
sga index --no-reverse -a ropebwt -t 1 spleen2_SE.fastq & 
